server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://scaufat.cn:3306/scauacm?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: 631665391
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
swagger:
  base-path: /**
  base-package: 'cn.edu.scau.acm.acmer'

